### ISSUE TITLE
Support Stream API

### ISSUE THREAD

**Issue by satouriko** [Coxxs/RCNB.js#4]
To handle a large bundle of data encoding, with javascript's wonderful stream support and well-known functional programing paradigm.

https://nodejs.org/api/stream.html
https://developer.mozilla.org/en-US/docs/Web/API/Streams_API

**Comment by satouriko** [comment]
https://nodejs.org/api/stream.html#stream_implementing_a_transform_stream
https://streams.spec.whatwg.org/#ts-class-definition

**Comment by Coxxs** [comment]
Added in https://github.com/rcnbapp/RCNB.js/commit/5317ef061ff557f3c85965d22512b7926072de72 , thanks to @momocow .
